"""add auth fields

Revision ID: 487e7af9bc12
Revises: eb719c984d34
Create Date: 2026-06-13 20:32:30.116673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '487e7af9bc12'
down_revision: Union[str, Sequence[str], None] = 'eb719c984d34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('magic_link_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_magic_link_token_token_hash'), 'magic_link_token', ['token_hash'], unique=True)
    op.create_index(op.f('ix_magic_link_token_user_id'), 'magic_link_token', ['user_id'], unique=False)
    op.add_column('user', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # WARNING: destructive. Dropping 'password_hash' destroys any stored
    # password hashes, and dropping 'magic_link_token' destroys in-flight
    # magic-link tokens. Only run before real user data exists.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    op.drop_index(op.f('ix_magic_link_token_user_id'), table_name='magic_link_token')
    op.drop_index(op.f('ix_magic_link_token_token_hash'), table_name='magic_link_token')
    op.drop_table('magic_link_token')
    # ### end Alembic commands ###
