"""initial schema

Revision ID: eb719c984d34
Revises: 
Create Date: 2026-06-13 14:19:18.903961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eb719c984d34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_user_id'), 'project', ['user_id'], unique=False)
    op.create_table('element',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pattern_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('repeat_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_element_project_id'), 'element', ['project_id'], unique=False)
    op.create_table('element_repetition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('repetition_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['element_id'], ['element.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('element_id', 'repetition_number')
    )
    op.create_index(op.f('ix_element_repetition_element_id'), 'element_repetition', ['element_id'], unique=False)
    op.create_table('row',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['element_id'], ['element.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('element_id', 'position')
    )
    op.create_index(op.f('ix_row_element_id'), 'row', ['element_id'], unique=False)
    op.create_table('row_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('element_repetition_id', sa.Integer(), nullable=False),
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('not_started', 'in_progress', 'done', name='rowstateenum'), nullable=False),
    sa.Column('stitch_position', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['element_repetition_id'], ['element_repetition.id'], ),
    sa.ForeignKeyConstraint(['row_id'], ['row.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('element_repetition_id', 'row_id')
    )
    op.create_index(op.f('ix_row_state_element_repetition_id'), 'row_state', ['element_repetition_id'], unique=False)
    op.create_index(op.f('ix_row_state_row_id'), 'row_state', ['row_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_row_state_row_id'), table_name='row_state')
    op.drop_index(op.f('ix_row_state_element_repetition_id'), table_name='row_state')
    op.drop_table('row_state')
    sa.Enum('not_started', 'in_progress', 'done', name='rowstateenum').drop(op.get_bind(), checkfirst=False)
    op.drop_index(op.f('ix_row_element_id'), table_name='row')
    op.drop_table('row')
    op.drop_index(op.f('ix_element_repetition_element_id'), table_name='element_repetition')
    op.drop_table('element_repetition')
    op.drop_index(op.f('ix_element_project_id'), table_name='element')
    op.drop_table('element')
    op.drop_index(op.f('ix_project_user_id'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
